/** Metadata about the built-in resume template for deterministic ATS audits */
export const RESUME_TEMPLATE_METADATA = {
  layoutMode: "single-column" as const,
  columnCount: 1,
  usesTables: false,
  usesTextBoxes: false,
  usesIcons: false,
  usesProgressBars: false,
  usesRatingCircles: false,
  usesFloatingElements: false,
  usesMultiColumnSkillsGrid: false,
  usesTwoColumnOptionalGrid: false,
  primaryFont: "Helvetica, Arial, sans-serif",
  headingFont: "Helvetica, Arial, sans-serif",
  bodyFontSizePt: 10.5,
  headingFontSizePt: 12,
  nameFontSizePt: 18,
  sectionOrder: [
    "Professional Summary",
    "Skills",
    "Work Experience",
    "Education",
    "Certifications",
    "Projects",
    "Languages",
    "Key Achievements",
    "Interests",
    "Additional Information",
  ],
  preferredSectionLabels: {
    summary: "Professional Summary",
    experience: "Work Experience",
    education: "Education",
    skills: "Skills",
    certifications: "Certifications",
    projects: "Projects",
  },
  contactUsesLabels: true,
  exportFormat: "text-based-pdf" as const,
};
